import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StarknetProvider } from "@/components/starknet-provider";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { WalletProvider } from "../context/WalletContext";
import { ElectionIdProvider } from "../context/ElectionIdContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StarknetProvider>
          <WalletProvider>
            <ElectionIdProvider>
              <div className=" text-[#000]">
                <Navbar />
                <div className="pt-24 text-[#000] bg-[#f7ebeb] pb-24">
                  <main>{children}</main>
                </div>
                <Footer />
              </div>
            </ElectionIdProvider>
          </WalletProvider>
        </StarknetProvider>
      </body>
    </html>
  );
}
